### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by trevorskaggs** [pirandig/django-zxcvbn#2]
When running a ```pip install django-zxcvbn``` I get a ```No distributions at all found for django-zxcvbn```.

Additionally could you tag a version/release?

**Comment by vdboor** [comment]
@pirandig could you look into this? I also get this error

**Comment by atkinson** [comment]
@vdboor this hasn't been maintained for a long time. I suggest you check out https://pypi.python.org/pypi/django-zxcvbn-password

**Comment by vdboor** [comment]
Thanks for mentioning the alternative. Perhaps it would be useful to mention this at the GitHub index page too?
